version: 2
updates:
  - package-ecosystem: npm
    directory: platform
    schedule:
      interval: weekly
    groups:
      platform-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: deps
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: platform/archestra-rs
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: deps
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: ai-labs
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: deps
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: deps
    cooldown:
      default-days: 7
