-- Intentionally a no-op. --
--
-- This migration originally ran a single unbounded UPDATE that set
-- interactions.external_agent_id = 'anthropic_claude' for historical Claude rows
-- (session_source 'claude_code' / 'claude_desktop', external_agent_id IS NULL).
--
-- interactions is the largest table in the product, and no index can narrow that
-- predicate: external_agent_id is NULL for ~every historical row (so its index is
-- useless for IS NULL) and session_source is unindexed. The statement therefore
-- does a full-table scan plus a row rewrite of every matching row. Because
-- migrations run inside the blocking pre-upgrade hook Job, it exceeds the job
-- deadline, which fails and rolls back the ENTIRE upgrade on every cluster (and
-- blocks every later migration behind it). It has never applied anywhere.
--
-- The backfill is data-only (no schema change) and cosmetic: it only lets the
-- /llm/logs "Client" filter surface pre-existing Claude rows. New rows already
-- get external_agent_id at write time (auto-discovery), so nothing depends on
-- this at runtime. It is neutralized here rather than deleted so the journal slot
-- and every migration after it stay in order.
--
-- If historical coverage is still wanted, run the backfill out-of-band as a
-- batched, resumable job (idempotent via the IS NULL guard) that commits in small
-- chunks and never blocks the migration path.
